<?php

namespace Database\Seeders;

use App\Models\Penduduk;
use App\Models\PendudukMutasi;
use App\Models\User;
use Illuminate\Database\Seeder;

class PendudukSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $staffUser = User::where('email', 'staff@desa.id')->first();
        $adminUser = User::where('email', 'admin@desa.id')->first();
        $createdById = $staffUser?->id ?? $adminUser?->id;

        $residents = [
            // Keluarga 1: Bapak Asep Suhendar
            [
                'nik' => '3202111504700001',
                'no_kk' => '3202111504700001',
                'nama_lengkap' => 'Asep Suhendar',
                'tempat_lahir' => 'Sukabumi',
                'tanggal_lahir' => '1970-04-15',
                'jenis_kelamin' => 'L',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'SLTA/Sederajat',
                'pekerjaan' => 'Petani',
                'status_perkawinan' => 'kawin',
                'status_dalam_keluarga' => 'kepala_keluarga',
                'kewarganegaraan' => 'WNI',
                'golongan_darah' => 'O',
                'alamat_lengkap' => 'Kp. Cikole RT 001 RW 002 Desa Sukamaju',
                'rt' => '001',
                'rw' => '002',
                'dusun' => 'Cikole',
                'telepon' => '082112340001',
                'sumber_data' => 'prodeskel',
                'status_penduduk' => 'tetap',
            ],
            [
                'nik' => '3202114508730001',
                'no_kk' => '3202111504700001',
                'nama_lengkap' => 'Siti Rohmah',
                'tempat_lahir' => 'Sukabumi',
                'tanggal_lahir' => '1973-08-05',
                'jenis_kelamin' => 'P',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'SLTP/Sederajat',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'status_perkawinan' => 'kawin',
                'status_dalam_keluarga' => 'istri',
                'kewarganegaraan' => 'WNI',
                'golongan_darah' => 'A',
                'alamat_lengkap' => 'Kp. Cikole RT 001 RW 002 Desa Sukamaju',
                'rt' => '001',
                'rw' => '002',
                'dusun' => 'Cikole',
                'telepon' => null,
                'sumber_data' => 'prodeskel',
                'status_penduduk' => 'tetap',
            ],
            [
                'nik' => '3202110206050001',
                'no_kk' => '3202111504700001',
                'nama_lengkap' => 'Rizki Maulana Suhendar',
                'tempat_lahir' => 'Sukabumi',
                'tanggal_lahir' => '2005-06-02',
                'jenis_kelamin' => 'L',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'SLTA/Sederajat',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'status_perkawinan' => 'belum_kawin',
                'status_dalam_keluarga' => 'anak',
                'kewarganegaraan' => 'WNI',
                'golongan_darah' => 'O',
                'alamat_lengkap' => 'Kp. Cikole RT 001 RW 002 Desa Sukamaju',
                'rt' => '001',
                'rw' => '002',
                'dusun' => 'Cikole',
                'telepon' => '083112340001',
                'sumber_data' => 'manual',
                'status_penduduk' => 'tetap',
            ],
            [
                'nik' => '3202114910130001',
                'no_kk' => '3202111504700001',
                'nama_lengkap' => 'Nur Fadilah Suhendar',
                'tempat_lahir' => 'Sukabumi',
                'tanggal_lahir' => '2013-10-09',
                'jenis_kelamin' => 'P',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'Belum Tamat SD',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'status_perkawinan' => 'belum_kawin',
                'status_dalam_keluarga' => 'anak',
                'kewarganegaraan' => 'WNI',
                'golongan_darah' => 'A',
                'alamat_lengkap' => 'Kp. Cikole RT 001 RW 002 Desa Sukamaju',
                'rt' => '001',
                'rw' => '002',
                'dusun' => 'Cikole',
                'telepon' => null,
                'sumber_data' => 'manual',
                'status_penduduk' => 'tetap',
            ],

            // Keluarga 2: H. Dedi Supriadi
            [
                'nik' => '3202111203800002',
                'no_kk' => '3202111203800002',
                'nama_lengkap' => 'H. Dedi Supriadi',
                'tempat_lahir' => 'Cianjur',
                'tanggal_lahir' => '1980-03-12',
                'jenis_kelamin' => 'L',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'Diploma IV/S1',
                'pekerjaan' => 'Pedagang',
                'status_perkawinan' => 'kawin',
                'status_dalam_keluarga' => 'kepala_keluarga',
                'kewarganegaraan' => 'WNI',
                'golongan_darah' => 'B',
                'alamat_lengkap' => 'Kp. Sukasari RT 003 RW 001 Desa Sukamaju',
                'rt' => '003',
                'rw' => '001',
                'dusun' => 'Sukasari',
                'telepon' => '081234567890',
                'sumber_data' => 'prodeskel',
                'status_penduduk' => 'tetap',
            ],
            [
                'nik' => '3202115304830002',
                'no_kk' => '3202111203800002',
                'nama_lengkap' => 'Hj. Imas Nuraeni',
                'tempat_lahir' => 'Sukabumi',
                'tanggal_lahir' => '1983-04-13',
                'jenis_kelamin' => 'P',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'SLTA/Sederajat',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'status_perkawinan' => 'kawin',
                'status_dalam_keluarga' => 'istri',
                'kewarganegaraan' => 'WNI',
                'golongan_darah' => 'B',
                'alamat_lengkap' => 'Kp. Sukasari RT 003 RW 001 Desa Sukamaju',
                'rt' => '003',
                'rw' => '001',
                'dusun' => 'Sukasari',
                'telepon' => null,
                'sumber_data' => 'prodeskel',
                'status_penduduk' => 'tetap',
            ],
            [
                'nik' => '3202111507100002',
                'no_kk' => '3202111203800002',
                'nama_lengkap' => 'Muhamad Fauzan Supriadi',
                'tempat_lahir' => 'Sukabumi',
                'tanggal_lahir' => '2010-07-15',
                'jenis_kelamin' => 'L',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'SLTP/Sederajat',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'status_perkawinan' => 'belum_kawin',
                'status_dalam_keluarga' => 'anak',
                'kewarganegaraan' => 'WNI',
                'golongan_darah' => 'A',
                'alamat_lengkap' => 'Kp. Sukasari RT 003 RW 001 Desa Sukamaju',
                'rt' => '003',
                'rw' => '001',
                'dusun' => 'Sukasari',
                'telepon' => null,
                'sumber_data' => 'manual',
                'status_penduduk' => 'tetap',
            ],

            // Keluarga 3: Ade Suryadi
            [
                'nik' => '3202110809750003',
                'no_kk' => '3202110809750003',
                'nama_lengkap' => 'Ade Suryadi',
                'tempat_lahir' => 'Sukabumi',
                'tanggal_lahir' => '1975-09-08',
                'jenis_kelamin' => 'L',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'SLTA/Sederajat',
                'pekerjaan' => 'Buruh Harian Lepas',
                'status_perkawinan' => 'kawin',
                'status_dalam_keluarga' => 'kepala_keluarga',
                'kewarganegaraan' => 'WNI',
                'golongan_darah' => 'AB',
                'alamat_lengkap' => 'Kp. Karangtengah RT 002 RW 004 Desa Sukamaju',
                'rt' => '002',
                'rw' => '004',
                'dusun' => 'Karangtengah',
                'telepon' => '087891234500',
                'sumber_data' => 'migrasi_legacy',
                'status_penduduk' => 'tetap',
            ],
            [
                'nik' => '3202114210780003',
                'no_kk' => '3202110809750003',
                'nama_lengkap' => 'Ai Nuraeni Suryadi',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1978-10-02',
                'jenis_kelamin' => 'P',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'SLTP/Sederajat',
                'pekerjaan' => 'Ibu Rumah Tangga',
                'status_perkawinan' => 'kawin',
                'status_dalam_keluarga' => 'istri',
                'kewarganegaraan' => 'WNI',
                'golongan_darah' => null,
                'alamat_lengkap' => 'Kp. Karangtengah RT 002 RW 004 Desa Sukamaju',
                'rt' => '002',
                'rw' => '004',
                'dusun' => 'Karangtengah',
                'telepon' => null,
                'sumber_data' => 'migrasi_legacy',
                'status_penduduk' => 'tetap',
            ],

            // Individu Lainnya & Mutasi
            [
                'nik' => '3202111806920004',
                'no_kk' => '3202111806920004',
                'nama_lengkap' => 'Yudi Permana',
                'tempat_lahir' => 'Sukabumi',
                'tanggal_lahir' => '1992-06-18',
                'jenis_kelamin' => 'L',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'Diploma IV/S1',
                'pekerjaan' => 'PNS',
                'status_perkawinan' => 'kawin',
                'status_dalam_keluarga' => 'kepala_keluarga',
                'kewarganegaraan' => 'WNI',
                'golongan_darah' => 'O',
                'alamat_lengkap' => 'Kp. Cikole RT 001 RW 003 Desa Sukamaju',
                'rt' => '001',
                'rw' => '003',
                'dusun' => 'Cikole',
                'telepon' => '081298765432',
                'sumber_data' => 'manual',
                'status_penduduk' => 'pindah',
            ],
            [
                'nik' => '3202118506450005',
                'no_kk' => '3202110809750003',
                'nama_lengkap' => 'Sarinem',
                'tempat_lahir' => 'Sukabumi',
                'tanggal_lahir' => '1945-06-25',
                'jenis_kelamin' => 'P',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'Tidak/Belum Sekolah',
                'pekerjaan' => null,
                'status_perkawinan' => 'cerai_mati',
                'status_dalam_keluarga' => 'famili_lain',
                'kewarganegaraan' => 'WNI',
                'golongan_darah' => null,
                'alamat_lengkap' => 'Kp. Karangtengah RT 002 RW 004 Desa Sukamaju',
                'rt' => '002',
                'rw' => '004',
                'dusun' => 'Karangtengah',
                'telepon' => null,
                'sumber_data' => 'migrasi_legacy',
                'status_penduduk' => 'tetap',
            ],
            [
                'nik' => '3204150703950001',
                'no_kk' => '3204150703950001',
                'nama_lengkap' => 'Budi Santoso',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir' => '1995-03-07',
                'jenis_kelamin' => 'L',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'Diploma IV/S1',
                'pekerjaan' => 'Wiraswasta',
                'status_perkawinan' => 'belum_kawin',
                'status_dalam_keluarga' => 'kepala_keluarga',
                'kewarganegaraan' => 'WNI',
                'golongan_darah' => 'A',
                'alamat_lengkap' => 'Kp. Sukasari RT 004 RW 001 Desa Sukamaju',
                'rt' => '004',
                'rw' => '001',
                'dusun' => 'Sukasari',
                'telepon' => '089512345678',
                'sumber_data' => 'manual',
                'status_penduduk' => 'tetap',
            ],
            [
                'nik' => '3202110203880006',
                'no_kk' => '3202110203880000',
                'nama_lengkap' => 'Jajang Kurniawan',
                'tempat_lahir' => 'Sukabumi',
                'tanggal_lahir' => '1988-03-02',
                'jenis_kelamin' => 'L',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'SLTA/Sederajat',
                'pekerjaan' => 'Petani',
                'status_perkawinan' => 'kawin',
                'status_dalam_keluarga' => 'kepala_keluarga',
                'kewarganegaraan' => 'WNI',
                'golongan_darah' => null,
                'alamat_lengkap' => 'Kp. Cikole RT 005 RW 001 Desa Sukamaju',
                'rt' => '005',
                'rw' => '001',
                'dusun' => 'Cikole',
                'telepon' => null,
                'sumber_data' => 'manual',
                'status_penduduk' => 'tetap',
            ],
            [
                'nik' => '3202115504910006',
                'no_kk' => '3202110203880000',
                'nama_lengkap' => 'Dewi Rahayu',
                'tempat_lahir' => 'Sukabumi',
                'tanggal_lahir' => '1991-04-15',
                'jenis_kelamin' => 'P',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'SLTA/Sederajat',
                'pekerjaan' => 'Pedagang',
                'status_perkawinan' => 'kawin',
                'status_dalam_keluarga' => 'istri',
                'kewarganegaraan' => 'WNI',
                'golongan_darah' => null,
                'alamat_lengkap' => 'Kp. Cikole RT 005 RW 001 Desa Sukamaju',
                'rt' => '005',
                'rw' => '001',
                'dusun' => 'Cikole',
                'telepon' => null,
                'sumber_data' => 'manual',
                'status_penduduk' => 'tetap',
            ],
            [
                'nik' => '3202112501200006',
                'no_kk' => '3202110203880000',
                'nama_lengkap' => 'Ikhsan Maulana',
                'tempat_lahir' => 'Sukabumi',
                'tanggal_lahir' => '2020-01-25',
                'jenis_kelamin' => 'L',
                'agama' => 'Islam',
                'pendidikan_terakhir' => null,
                'pekerjaan' => null,
                'status_perkawinan' => 'belum_kawin',
                'status_dalam_keluarga' => 'anak',
                'kewarganegaraan' => 'WNI',
                'golongan_darah' => null,
                'alamat_lengkap' => 'Kp. Cikole RT 005 RW 001 Desa Sukamaju',
                'rt' => '005',
                'rw' => '001',
                'dusun' => 'Cikole',
                'telepon' => null,
                'sumber_data' => 'manual',
                'status_penduduk' => 'tetap',
            ],
            [
                'nik' => '3202111012960007',
                'no_kk' => '3202111012960000',
                'nama_lengkap' => 'Dedi Wahyudi',
                'tempat_lahir' => 'Sukabumi',
                'tanggal_lahir' => '1996-12-10',
                'jenis_kelamin' => 'L',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'SLTA/Sederajat',
                'pekerjaan' => 'Karyawan Swasta',
                'status_perkawinan' => 'belum_kawin',
                'status_dalam_keluarga' => 'kepala_keluarga',
                'kewarganegaraan' => 'WNI',
                'golongan_darah' => null,
                'alamat_lengkap' => 'Kp. Sukasari RT 006 RW 002 Desa Sukamaju',
                'rt' => '006',
                'rw' => '002',
                'dusun' => 'Sukasari',
                'telepon' => null,
                'sumber_data' => 'manual',
                'status_penduduk' => 'tetap',
            ],
            [
                'nik' => '3202114903840008',
                'no_kk' => '3202114903840000',
                'nama_lengkap' => 'Tini Andriani',
                'tempat_lahir' => 'Sukabumi',
                'tanggal_lahir' => '1984-03-09',
                'jenis_kelamin' => 'P',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'Diploma IV/S1',
                'pekerjaan' => 'Guru',
                'status_perkawinan' => 'kawin',
                'status_dalam_keluarga' => 'kepala_keluarga',
                'kewarganegaraan' => 'WNI',
                'golongan_darah' => null,
                'alamat_lengkap' => 'Kp. Karangtengah RT 007 RW 003 Desa Sukamaju',
                'rt' => '007',
                'rw' => '003',
                'dusun' => 'Karangtengah',
                'telepon' => null,
                'sumber_data' => 'manual',
                'status_penduduk' => 'tetap',
            ],
            [
                'nik' => '3202110502010009',
                'no_kk' => '3202114903840000',
                'nama_lengkap' => 'Ahmad Fauzi Ramadan',
                'tempat_lahir' => 'Sukabumi',
                'tanggal_lahir' => '2001-02-05',
                'jenis_kelamin' => 'L',
                'agama' => 'Islam',
                'pendidikan_terakhir' => 'SLTA/Sederajat',
                'pekerjaan' => 'Pelajar/Mahasiswa',
                'status_perkawinan' => 'belum_kawin',
                'status_dalam_keluarga' => 'anak',
                'kewarganegaraan' => 'WNI',
                'golongan_darah' => null,
                'alamat_lengkap' => 'Kp. Karangtengah RT 007 RW 003 Desa Sukamaju',
                'rt' => '007',
                'rw' => '003',
                'dusun' => 'Karangtengah',
                'telepon' => null,
                'sumber_data' => 'manual',
                'status_penduduk' => 'tetap',
            ],
        ];

        foreach ($residents as $res) {
            Penduduk::updateOrCreate(['nik' => $res['nik']], $res);
        }

        // Catat mutasi sample
        if ($createdById) {
            $yudi = Penduduk::where('nik', '3202111806920004')->first();
            if ($yudi) {
                PendudukMutasi::firstOrCreate(
                    ['penduduk_id' => $yudi->id, 'jenis_mutasi' => 'pindah_keluar'],
                    [
                        'tanggal_mutasi' => '2026-03-15',
                        'keterangan' => 'Pindah ke Kota Bogor mengikuti penempatan kerja PNS.',
                        'created_by' => $createdById,
                    ]
                );
            }

            $ikhsan = Penduduk::where('nama_lengkap', 'Ikhsan Maulana')->first();
            if ($ikhsan) {
                PendudukMutasi::firstOrCreate(
                    ['penduduk_id' => $ikhsan->id, 'jenis_mutasi' => 'lahir'],
                    [
                        'tanggal_mutasi' => '2020-01-25',
                        'keterangan' => 'Kelahiran di RSUD Sukabumi. Berat badan 3,2 kg.',
                        'created_by' => $createdById,
                    ]
                );
            }

            $budi = Penduduk::where('nama_lengkap', 'Budi Santoso')->first();
            if ($budi) {
                PendudukMutasi::firstOrCreate(
                    ['penduduk_id' => $budi->id, 'jenis_mutasi' => 'pindah_masuk'],
                    [
                        'tanggal_mutasi' => '2025-11-01',
                        'keterangan' => 'Pindah masuk dari Kab. Bogor. Membuka usaha konveksi di desa.',
                        'created_by' => $createdById,
                    ]
                );
            }
        }
    }
}
